name: Upload release assets

permissions:
  contents: write

on:
  release:
    types:
      - created

jobs:
  build-deb:
    name: Create zip for publishing
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Create zip
        run: |
          cd gestureImprovements@gestures
          zip -r ../gestureImprovements@gestures.zip *
          cd ..

      - name: Upload package
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./gestureImprovements@gestures.zip
          asset_name: gestureImprovements@gestures.zip
          tag: ${{ github.ref }}
